### ISSUE TITLE
Device state never reflected in ImperiHome

### ISSUE THREAD

**Issue by ghost** [pdegeus/openhab2-addons#4]
Hello,

thanks for your effort to give us a reliable alternative to the OpenHAB UI that still is sometimes laggy or requires manual refreshes.

I followed the description and got ImperiHome up and running. However, on every refresh, the devices are set to default state (e.g., light to off or MultiSwitches to 1st alternative in mapping) instead of the correct state of the device.

Since I configured all according to the Wiki, I suppose it's a bug somewhere. However, the openHAB2 logs show nothing special I could report.

Do you have any suggestion of how to fix this? Thanks a lot!

EDIT: Actually under the URL "imperihome/iss/devices" the devices report no state either (here's one example):
`{"id":"e2764bfe589e05ab007cffb28407f0f407f03e01","name":"Wallswitch","room":"34b18735d143075b63c733dbf5cdfd2de9b2ba7a","type":"DevSwitch","params":[{"key":"defaultIcon","value":"http://openhab/icon/light"}]}`

**Comment by pdegeus** [comment]
Hi, thanks for reporting. I think you're affected by this bug in Eclipse Smarthome (the framework powering openHAB): https://github.com/eclipse/smarthome/issues/3160

You can work around it by using a single items file instead of multiple, or by manually stopping and starting the ImperiHome OSGi bundle using the openHAB client console.

The latest snapshot build on my server contains a workaround for the bug, so you can also give that a try:
https://dl.dvelop.nl/oh-imperihome/

**Comment by ghost** [comment]
Hi @pdegeus,

thanks for your help. I'll try that. Do you have an idea when your workaround package will make it into the repos so I can install it in PaperUI via uninstall/install of ImperiHome add-on?

Cheers!

**Comment by pdegeus** [comment]
If you're using the beta package that could take a while, probably a month or more. I haven't created a pull request yet for these changes. After I do so (planning to do this weekend) I'll take a few days to be accepted and the changes to land in the snapshot build.

**Comment by ghost** [comment]
Thanks. It seems to be working with the latest build.
